# Intro
This notebook just gives statistics about our datast

## Reference
https://github.com/karpathy/nn-zero-to-hero/blob/master/lectures/makemore/makemore_part1_bigrams.ipynb

In [1]:
names = open('names.txt', 'r').read().split()

FileNotFoundError: [Errno 2] No such file or directory: 'names.txt'

In [ ]:
len(names)

32033

In [3]:
min(len(x) for x in names)

2

In [4]:
max(len(x) for x in names)

15

In [2]:
 ## Prepare dataset

import pandas as pd


## Loading arabic names
a1 = pd.read_csv('data/females_en.csv')
a2 = pd.read_csv('data/males_en.csv')

## we need to do an experiment without this
a3 = pd.read_csv('data/KDBVAROM.txt', sep='\t')

In [3]:
arabic_names = pd.concat([a1.Name , a2.Name , a3.Roman])

arabic_names = pd.DataFrame(columns=['name'], data=arabic_names)

In [4]:
arabic_names

              name
0          aabidah
1          aabirah
2           aabish
3            aadab
4           aadila
...            ...
5056     Cabdullah
5057    Cabdullahi
5058      Cabdulle
5059  Cabdulqaadir
5060   Cabdulqadir

[9572 rows x 1 columns]

In [6]:
# remove extra a from names 
for i in arabic_names.index:
    if arabic_names.iloc[i]['name'].startswith('aa'):
        arabic_names.at[i,'name'] = arabic_names.iloc[i]['name'][1:]

arabic_names

              name
0           abidah
1           abirah
2            abish
3             adab
4            adila
...            ...
5056     Cabdullah
5057    Cabdullahi
5058      Cabdulle
5059  Cabdulqaadir
5060   Cabdulqadir

[9572 rows x 1 columns]

In [5]:
with open('combined_english_names.txt','a') as f:
    for l in arabic_names.name:
        f.write(l + '\n')

In [61]:
arabic_names.describe()

        name
count   9572
unique  9391
top      ala
freq       5

In [62]:
arabic_names = arabic_names.drop_duplicates()

In [63]:
arabic_names.describe()

          name
count     9391
unique    9391
top     abidah
freq         1

In [64]:
arabic_names["name"].str.len().max(), arabic_names["name"].str.len().min()

(17, 2)

In [68]:

cnt = 0
for x in arabic_names.name:
    if ' ' in x:
        cnt +=1

cnt

1528

In [71]:
arabic_names.name = arabic_names.name.map( lambda x: x.replace(' ', '-'))

/tmp/ipykernel_3604803/1522538124.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  arabic_names.name = arabic_names.name.map( lambda x: x.replace(' ', '-'))

In [72]:

cnt = 0
for x in arabic_names.name:
    if ' ' in x:
        cnt +=1
cnt

0

In [89]:
###### FIRST USING BI_GRAMS ##########

bi = {}

for w in arabic_names.name.iloc:
    mod_w = ['<S>'] + list(w) + ['<E>']
    for b1,b2  in zip(mod_w, mod_w[1:]):
        # print (b1,b2)
        bi[ (b1,b2)]  = bi.get((b1,b2) ,0)  + 1

In [90]:
bi = dict(sorted(bi.items(), key= lambda x: x[1], reverse=True ))

In [91]:
bi

{('b', 'd'): 5186,
 ('<S>', 'A'): 5010,
 ('A', 'b'): 4994,
 ('d', 'u'): 2656,
 ('u', 'l'): 2303,
 ('a', 'h'): 2000,
 ('h', 'a'): 1797,
 ('r', 'a'): 1416,
 ('a', 'l'): 1336,
 ('m', 'a'): 1310,
 ('h', '<E>'): 1247,
 ('r', '<E>'): 1225,
 ('a', '<E>'): 1167,
 ('a', 'n'): 1110,
 ('n', '<E>'): 1085,
 ('l', '-'): 1067,
 ('a', 'r'): 935,
 ('m', '<E>'): 924,
 ('l', 'a'): 889,
 ('a', 'm'): 879,
 ('a', 'd'): 802,
 ('d', '<E>'): 792,
 ('e', 'e'): 772,
 ('d', 'i'): 759,
 ('s', 'a'): 707,
 ('d', 'e'): 706,
 ('s', 'h'): 703,
 ('<S>', 'a'): 673,
 ('n', 'a'): 663,
 ('a', 'b'): 662,
 ('o', 'u'): 660,
 ('e', 'l'): 653,
 ('a', 's'): 648,
 ('<S>', 's'): 644,
 ('d', 'o'): 631,
 ('d', 'a'): 618,
 ('i', 'm'): 535,
 ('k', 'a'): 532,
 ('h', 'i'): 501,
 ('b', 'a'): 499,
 ('i', 'r'): 495,
 ('a', 'z'): 493,
 ('e', 'r'): 493,
 ('<S>', 'm'): 491,
 ('w', 'a'): 460,
 ('i', '<E>'): 447,
 ('a', 'k'): 445,
 ('f', 'a'): 440,
 ('u', 'r'): 434,
 ('h', 'm'): 420,
 ('a', 'y'): 418,
 ('z', 'a'): 410,
 ('i', 'd'): 409,
 ('l', 'r'): 407,
 ('d', '-'): 403,
 ('t', 'a'): 394,
 ('a', 'a'): 386,
 ('i', 'l'): 385,
 ('a', 't'): 382,
 ('y', 'a'): 381,
 ('a', 'f'): 375,
 ('r', 'i'): 372,
 ('a', 'i'): 357,
 ('l', 'i'): 353,
 ('<S>', 'n'): 346,
 ('l', 'k'): 336,
 ('l', '<E>'): 330,
 ('m', 'u'): 329,
 ('l', 'm'): 325,
 ('l', 'h'): 323,
 ('b', '<E>'): 312,
 ('e', 'm'): 304,
 ('i', 'n'): 302,
 ('l', 'l'): 295,
 ('k', 'h'): 283,
 ('j', 'a'): 281,
 ('m', 'o'): 281,
 ('<S>', 'r'): 271,
 ('k', '<E>'): 264,
 ('<S>', 'h'): 264,
 ('-', 'a'): 263,
 ('m', 'i'): 262,
 ('e', '<E>'): 258,
 ('u', 's'): 258,
 ('e', 'd'): 256,
 ('h', 'e'): 256,
 ('z', '<E>'): 248,
 ('n', 'i'): 246,
 ('m', 'e'): 246,
 ('e', 'n'): 245,
 ('o', 'v'): 245,
 ('s', 'i'): 242,
 ('r', 'e'): 241,
 ('f', '<E>'): 237,
 ('-', 'r'): 230,
 ('i', 'y'): 222,
 ('q', 'a'): 221,
 ('i', 's'): 220,
 ('u', 'm'): 219,
 ('<S>', 'f'): 207,
 ('g', 'a'): 204,
 ('s', 's'): 201,
 ('h', 'u'): 201,
 ('i', 'z'): 200,
 ('z', 'i'): 198,
 ('u', 'a'): 195,
 ('o', 'o'): 189,
 ('q', '<E>'): 185,
 ('l', 'e'): 184,
 ('s', 'e'): 183,
 ('d', 'l'): 178,
 ('n', 'e'): 177,
 ('<S>', 'k'): 176,
 ('u', 'h'): 175,
 ('i', 'k'): 174,
 ('g', 'h'): 173,
 ('l', 's'): 173,
 ('<S>', 't'): 172,
 ('t', '<E>'): 171,
 ('a', 'q'): 170,
 ('d', 'r'): 169,
 ('a', 'j'): 168,
 ('o', 'r'): 167,
 ('-', 'e'): 165,
 ('r', 'h'): 164,
 ('i', 'f'): 162,
 ('a', 'w'): 161,
 ('e', 'h'): 159,
 ('v', 'a'): 156,
 ('<S>', 'z'): 156,
 ('f', 'i'): 155,
 ('i', 'b'): 154,
 ('-', 'm'): 150,
 ('u', 'k'): 145,
 ('i', 'a'): 142,
 ('l', 'g'): 142,
 ('<S>', 'j'): 140,
 ('b', 'i'): 139,
 ('<S>', 'b'): 137,
 ('u', 'n'): 137,
 ('<S>', 'i'): 136,
 ('-', 'h'): 136,
 ('r', 'r'): 134,
 ('u', '-'): 132,
 ('t', 'i'): 131,
 ('s', '<E>'): 130,
 ('v', '<E>'): 129,
 ('l', 'w'): 128,
 ('-', 'k'): 128,
 ('r', 'o'): 126,
 ('s', 'u'): 124,
 ('u', 'd'): 122,
 ('t', 'h'): 122,
 ('k', 'i'): 120,
 ('o', 'l'): 117,
 ('i', 'h'): 110,
 ('i', 'e'): 108,
 ('<S>', 'w'): 108,
 ('-', 'g'): 106,
 ('y', '<E>'): 104,
 ('u', 'b'): 103,
 ('k', 'o'): 101,
 ('i', 't'): 99,
 ('-', 's'): 97,
 ('z', 'e'): 94,
 ('j', 'i'): 92,
 ('n', 'o'): 91,
 ('r', 'u'): 91,
 ('k', 'e'): 89,
 ('l', 'q'): 88,
 ('o', 'h'): 86,
 ('i', 'q'): 82,
 ('e', 'z'): 82,
 ('u', 'f'): 82,
 ('m', 'm'): 81,
 ('f', 'e'): 79,
 ('e', 's'): 78,
 ('<S>', 'd'): 78,
 ('<S>', 'l'): 78,
 ('l', 'b'): 77,
 ('y', 'y'): 77,
 ('d', 'd'): 76,
 ('-', 'u'): 74,
 ('u', 'i'): 73,
 ('e', 'b'): 72,
 ('u', 't'): 72,
 ('d', 'h'): 72,
 ('e', 'i'): 72,
 ('t', 'e'): 71,
 ('k', 'u'): 71,
 ('o', 'n'): 70,
 ('n', 'u'): 70,
 ('<S>', 'u'): 70,
 ('b', 'e'): 69,
 ('a', 'g'): 69,
 ('k', 'r'): 66,
 ('e', 'f'): 65,
 ('f', 'f'): 65,
 ('-', 'w'): 64,
 ('j', 'e'): 63,
 ('h', 'r'): 63,
 ('h', 's'): 62,
 ('t', 't'): 61,
 ('l', 'j'): 61,
 ('<S>', 'g'): 60,
 ('<S>', 'q'): 60,
 ('l', 'n'): 60,
 ('z', 'z'): 59,
 ('f', 'o'): 58,
 ('s', 'o'): 57,
 ('l', 'f'): 57,
 ('b', 'u'): 56,
 ('<S>', 'y'): 56,
 ('m', 'n'): 55,
 ('l', 'u'): 54,
 ('a', 'u'): 53,
 ('b', 'b'): 53,
 ('o', 'm'): 53,
 ('n', 'n'): 52,
 ('e', 'k'): 51,
 ('u', '<E>'): 50,
 ('u', 'g'): 50,
 ('-', 'b'): 50,
 ('q', 'u'): 49,
 ('l', 't'): 47,
 ('u', 'w'): 47,
 ('y', 'm'): 46,
 ('y', 'e'): 45,
 ('u', 'j'): 45,
 ('a', 'e'): 44,
 ('y', 'u'): 44,
 ('u', 'q'): 43,
 ('e', 't'): 43,
 ('z', 'u'): 42,
 ('y', 'r'): 42,
 ('b', 'o'): 42,
 ('l', 'd'): 42,
 ('u', 'e'): 42,
 ('u', 'u'): 41,
 ('r', 's'): 40,
 ('h', 'o'): 40,
 ('t', 'o'): 39,
 ('q', 'i'): 39,
 ('w', 'i'): 39,
 ('j', 'u'): 39,
 ('r', 'z'): 39,
 ('-', 'l'): 39,
 ('h', 'k'): 38,
 ('s', 't'): 38,
 ('e', 'a'): 37,
 ('-', 'q'): 37,
 ('h', 'd'): 36,
 ('s', 'r'): 34,
 ('f', 'u'): 34,
 ('-', 'j'): 34,
 ('y', 'l'): 33,
 ('e', 'q'): 33,
 ('u', 'z'): 33,
 ('o', 'd'): 33,
 ('g', '<E>'): 33,
 ('s', 'l'): 32,
 ('y', 'd'): 32,
 ('k', 'k'): 32,
 ('i', 'g'): 31,
 ('s', 'm'): 31,
 ('l', 'o'): 31,
 ('a', 'o'): 31,
 ('r', 'y'): 30,
 ('h', 'n'): 30,
 ('o', 'e'): 30,
 ('r', '-'): 30,
 ('e', 'y'): 29,
 ('i', 'j'): 29,
 ('y', 's'): 29,
 ('g', 'e'): 29,
 ('g', 'i'): 29,
 ('t', 'u'): 28,
 ('z', 'o'): 28,
 ('d', 'y'): 28,
 ('d', 'j'): 27,
 ('-', 'n'): 27,
 ('j', '<E>'): 26,
 ('h', 'y'): 26,
 ('-', 'f'): 26,
 ('-', 'i'): 26,
 ('y', 'n'): 25,
 ('o', 's'): 25,
 ('h', 't'): 25,
 ('o', 'f'): 25,
 ('n', 'd'): 24,
 ('r', 'm'): 24,
 ('h', 'h'): 24,
 ('o', 't'): 24,
 ('m', 'r'): 23,
 ('<S>', 'e'): 23,
 ('y', 'o'): 23,
 ('a', 'c'): 23,
 ('n', 'y'): 22,
 ('f', 't'): 22,
 ('i', 'u'): 22,
 ('h', 'b'): 21,
 ('q', 'e'): 21,
 ('r', 'd'): 21,
 ('i', '-'): 21,
 ('l', 'z'): 20,
 ('y', 'i'): 20,
 ('c', 'a'): 20,
 ('w', 'w'): 19,
 ('y', 'b'): 19,
 ('b', 'r'): 18,
 ('h', 'l'): 18,
 ('c', 'h'): 18,
 ('h', 'f'): 18,
 ('o', 'k'): 18,
 ('c', 'k'): 18,
 ('o', '<E>'): 17,
 ('s', 'n'): 17,
 ('d', 's'): 17,
 ('e', 'g'): 17,
 ('n', 'z'): 16,
 ('w', 'e'): 16,
 ('A', 'a'): 16,
 ('j', 'l'): 15,
 ('l', 'v'): 15,
 ('o', 'b'): 15,
 ('a', 'v'): 15,
 ('p', 'a'): 15,
 ('e', '-'): 15,
 ('f', 'r'): 14,
 ('r', 'w'): 14,
 ('j', 'd'): 14,
 ('-', 'd'): 14,
 ('u', 'v'): 14,
 ('z', 'h'): 13,
 ('v', 'e'): 13,
 ('i', 'i'): 13,
 ('i', 'c'): 13,
 ('m', 's'): 12,
 ('e', 'j'): 12,
 ('z', 'm'): 12,
 ('n', 't'): 12,
 ('w', 'h'): 12,
 ('<S>', 'C'): 12,
 ('C', 'a'): 12,
 ('h', 'w'): 11,
 ('g', 'u'): 11,
 ('y', 'f'): 11,
 ('n', 's'): 11,
 ('o', 'z'): 10,
 ('v', 'i'): 10,
 ('m', 't'): 10,
 ('d', 'k'): 10,
 ('m', 'y'): 10,
 ('y', 'h'): 10,
 ('m', 'd'): 10,
 ('s', 'k'): 10,
 ('h', 'z'): 10,
 ('k', 'd'): 10,
 ('u', 'o'): 10,
 ('a', 'p'): 10,
 ('d', 'n'): 9,
 ('f', 's'): 9,
 ('m', 'j'): 9,
 ('s', 'b'): 9,
 ('w', 'l'): 9,
 ('d', 'w'): 9,
 ('w', 'z'): 9,
 ('o', 'w'): 9,
 ('y', 't'): 9,
 ('l', 'c'): 9,
 ('e', 'u'): 9,
 ('l', 'y'): 8,
 ('r', 'f'): 8,
 ('r', 'j'): 8,
 ('k', 'y'): 8,
 ('<S>', 'p'): 8,
 ('z', 'q'): 8,
 ('r', 't'): 8,
 ('z', 'y'): 8,
 ('i', 'w'): 8,
 ('s', '-'): 8,
 ('b', 'l'): 7,
 ('n', 'w'): 7,
 ('h', 'j'): 7,
 ('o', 'a'): 7,
 ('w', 's'): 7,
 ('j', 'j'): 7,
 ('o', 'i'): 7,
 ('z', 'n'): 7,
 ('<S>', 'o'): 7,
 ('m', 'z'): 7,
 ('w', 'o'): 7,
 ('q', 'q'): 7,
 ('v', 'o'): 7,
 ('e', 'w'): 7,
 ('-', 'c'): 7,
 ('m', 'b'): 6,
 ('n', 'b'): 6,
 ('s', 'f'): 6,
 ('r', 'q'): 6,
 ('b', 't'): 6,
 ('q', 'b'): 6,
 ('y', 'k'): 6,
 ('j', 'm'): 6,
 ('m', 'l'): 6,
 ('w', 'd'): 6,
 ('k', 's'): 6,
 ('b', 'h'): 6,
 ('g', 'o'): 6,
 ('o', 'g'): 6,
 ('d', 'f'): 6,
 ('i', 'o'): 6,
 ('n', 'j'): 5,
 ('r', 'v'): 5,
 ('z', 'r'): 5,
 ('<S>', 'c'): 5,
 ('q', 'r'): 5,
 ('z', 'l'): 5,
 ('y', 'z'): 5,
 ('t', 'l'): 5,
 ('i', 'v'): 5,
 ('j', 'r'): 4,
 ('t', 'y'): 4,
 ('z', 'k'): 4,
 ('w', 'r'): 4,
 ('s', 'w'): 4,
 ('k', 'w'): 4,
 ('t', 'f'): 4,
 ('h', 'v'): 4,
 ('w', 'u'): 4,
 ('u', 'y'): 4,
 ('f', 'w'): 4,
 ('r', 'b'): 4,
 ('o', 'q'): 4,
 ('w', 'f'): 4,
 ('-', 'z'): 4,
 ('a', '-'): 4,
 ('g', 'f'): 4,
 ('e', 'c'): 4,
 ('w', '<E>'): 4,
 ('d', 'q'): 4,
 ('p', 'p'): 4,
 ('e', 'v'): 3,
 ('f', 'y'): 3,
 ('k', 'l'): 3,
 ('n', 'g'): 3,
 ('s', 'y'): 3,
 ('t', 'b'): 3,
 ('n', 'f'): 3,
 ('f', 'z'): 3,
 ('k', 'm'): 3,
 ('j', 'o'): 3,
 ('n', 'v'): 3,
 ('b', 'n'): 3,
 ('n', 'h'): 3,
 ('r', 'n'): 3,
 ('f', 'l'): 3,
 ('r', 'g'): 3,
 ('o', 'j'): 3,
 ('d', 'b'): 3,
 ('z', 'w'): 3,
 ('d', 'm'): 3,
 ('w', 'b'): 3,
 ('m', 'k'): 3,
 ('<S>', 'v'): 3,
 ('q', 'o'): 3,
 ('q', 't'): 3,
 ('b', 'y'): 3,
 ('k', 'b'): 3,
 ('q', 'd'): 3,
 ('c', 'i'): 3,
 ('p', 'o'): 3,
 ('-', 'v'): 3,
 ('h', '-'): 3,
 ('-', 't'): 3,
 ('u', 'p'): 3,
 ('j', 'w'): 2,
 ('g', 'b'): 2,
 ('q', 's'): 2,
 ('t', 'r'): 2,
 ('r', 'k'): 2,
 ('t', 'm'): 2,
 ('u', 'c'): 2,
 ('z', 'd'): 2,
 ('n', 'k'): 2,
 ('w', 'n'): 2,
 ('w', 't'): 2,
 ('w', 'q'): 2,
 ('z', 'f'): 2,
 ('p', 'h'): 2,
 ('q', 'w'): 2,
 ('m', 'h'): 2,
 ('f', 'h'): 2,
 ('s', 'g'): 2,
 ('k', 't'): 2,
 ('w', 'g'): 2,
 ('h', 'q'): 2,
 ('g', 'd'): 2,
 ('c', 'e'): 2,
 ('d', 'g'): 2,
 ('c', '<E>'): 2,
 ('p', '<E>'): 2,
 ('-', 'o'): 2,
 ('k', '-'): 2,
 ('b', 'q'): 1,
 ('f', 'n'): 1,
 ('n', 'm'): 1,
 ('t', 'k'): 1,
 ('k', 'n'): 1,
 ('a', '/'): 1,
 ('/', 'u'): 1,
 ('j', 'n'): 1,
 ('h', '('): 1,
 ('(', 'i'): 1,
 ('t', ')'): 1,
 (')', '<E>'): 1,
 ('w', 'k'): 1,
 ('h', 'g'): 1,
 ('j', 'y'): 1,
 ('d', 'z'): 1,
 ('r', 'l'): 1,
 ('t', 'w'): 1,
 ('o', 'p'): 1,
 ('v', 'u'): 1,
 ('g', 'm'): 1,
 ('o', 'y'): 1,
 ('y', 'v'): 1,
 ('b', 's'): 1,
 ('b', 'z'): 1,
 ('t', 's'): 1,
 ('q', 'm'): 1,
 ('n', '.'): 1,
 ('.', '<E>'): 1,
 ('j', 't'): 1,
 ('n', 'q'): 1,
 ('p', 'e'): 1,
 ('f', 'd'): 1,
 ('f', 'q'): 1,
 ('y', 'j'): 1,
 ('q', 'y'): 1,
 ('g', 'n'): 1,
 ('w', 'y'): 1,
 ('m', 'g'): 1,
 ('i', 'p'): 1,
 ('j', 'b'): 1,
 ('g', 'g'): 1,
 ('q', 'f'): 1,
 ('b', 'w'): 1}